- hosts: myhosts
  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    become: true
    ansible.builtin.file:
      path: /tmp/e2e_test.txt
      state: touch
      mode: u=rw,g=r,o=r
      when: ansible_check_mode
  - name: Hello World!
    shell: echo "Hi! Ansible integration is working."