- hosts: myhosts
  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    become: true
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Touch the same file, but add/remove some permissions
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u+rw,g-wx,o-rwx