- hosts: myhosts
  tasks:
  - name: Install apache httpd  (state=present is optional)
    become: true
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present

- name: Include a play after another play
  ansible.builtin.import_playbook: playbook_1.yaml