
- hosts: myhosts
  tasks:
  - name: Skip planning
    set_fact:
      skip_planning: "{{ lookup('env', 'SPACELIFT_SKIP_PLANNING') | default('False', True) }}"

  - name: Hello World!
    shell: echo "Hi! Ansible integration is working."
    check_mode: false
    when: skip_planning != True

