- hosts: myhosts
  connection: local
  roles:
    - role: "local_dummy"
      become: false
    - role: webofmars.dummy
      become: false

  tasks:
  - name: Add a line to a file if the file, without passing regexp
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      line: "{{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }}"
      create: yes
  - name: Display /tmp/testfile contents
    command: cat /tmp/testfile
    register: command_output
  - name: Print to console
    debug:
      msg: "{{command_output.stdout}}"
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    become: false
    ignore_errors: yes
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Touch the other file, add other permissions
    become: false
    ignore_errors: yes
    ansible.builtin.file:
      path: /etc/foo2.conf
      state: touch
      mode: u+rw,g-wx,o-rwx
  - name: Install apache httpd  (state=present is optional)
    become: false
    ignore_unreachable: yes
    ignore_errors: yes
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present
  - name: Print a message
    loop: "{{ range(5) }}"
    ansible.builtin.debug:
      msg: 'I execute normally'
  - name: Print a message
    loop: "{{ range(10) }}"
    ansible.builtin.debug:
      msg: 'Dummy message'