- hosts: myhosts
  tasks:
  - name: Install apache httpd  (state=present is optional)
    become: true
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present
      when: ansible_check_mode
  - name: Install apache httpd  (state=present is optional)
    become: true
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: absent
      when: ansible_check_mode
  - name: Hello World!
    shell: echo "Hi! Ansible integration is working."