---
- name: Demo
  hosts: all
  connection: local
  tasks:
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      become: false
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        mode: u=rw,g=r,o=r
      loop:
        - 1.yaml
        - 2.yaml
        - a.yaml
        - b.yaml
        - cde.yaml
    - name: Add a line to a file if the file, without passing regexp
      when: not ansible_check_mode
      ansible.builtin.lineinfile:
        path: "{{ item.file_name }}"
        line: "natalia test"
        create: false
      loop:
        - { file_name: 1.yaml, other_prop: value }
        - { file_name: 2.yaml, other_prop: value }
        - { file_name: a.yaml, other_prop: value }
        - { file_name: b.yaml, other_prop: value }
        - { file_name: cde.yaml, other_prop: value }
        
    - name: Natalia test playbook
      when: not ansible_check_mode
      ansible.builtin.lineinfile:
        path: "{{ item.file_name }}"
        line: "natalia test"
        create: false
      loop:
        - { file_name: 1.yaml, other_prop: value }
        - { file_name: 2.yaml, other_prop: value }
        - { file_name: a.yaml, other_prop: value }
        - { file_name: b.yaml, other_prop: value }
        - { file_name: cde.yaml, other_prop: value }
