- name: DummyTest
  hosts: localhost
  connection: local
  roles:
    - role: webofmars.dummy
      become: false

  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    become: false
    ansible.builtin.file:
      path: /tmp/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Remove file
    become: false
    ansible.builtin.file:
      path: /tmp/foo.conf
      state: absent
  - name: Install apache httpd  (state=present is optional)
    become: true
    ignore_errors: true
    community.general.apk:
      name: apache2
      update_cache: yes
      state: present
  - name: Skipped example
    become: true
    when: false
    community.general.apk:
      name: apache2
      update_cache: yes
      state: present
 