- name: DummyTest
  hosts: localhost
  connection: local
  roles:
    - role: webofmars.dummy
      become: false

  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    become: false
    ansible.builtin.file:
      path: /tmp/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Touch the other file, add other permissions
    become: false
    ansible.builtin.file:
      path: /tmp/foo2.conf
      state: touch
      mode: u+rw,g-wx,o-rwx
  - name: Install apache httpd  (state=present is optional)
    become: false
    ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present

 