- name: will wait till reachable
  hosts: all
  gather_facts: false # we just created the EC2 machine, so we want for the machine to become accessible before gathering facts
  ignore_unreachable: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 180

    - name: Gather facts for the first time
      ansible.builtin.setup:

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Install apache packages
      become: true
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: "Creating Document root"
      become: true
      ansible.builtin.file:
        state: directory
        dest: "{{ doc_root }}"
        mode: 0701

    - name: "Creating Configuration root"
      become: true
      ansible.builtin.file:
        state: directory
        dest: "/etc/apache2/httpd/conf.d/"
        mode: 0701

    - name: "Configuration File"
      become: true
      ansible.builtin.template:
        src: "templates/webserver.j2"
        dest: "/etc/apache2/httpd/conf.d/new_conf.conf"
        mode: 0644
      notify: "server restart"

    - name: "Copy webpages"
      become: true
      ansible.builtin.template:
        src: "templates/webpage.j2"
        dest: "{{ doc_root }}/index.html"

    - name: ensure apache2 is running
      become: true
      ansible.builtin.service:
        name: apache2
        state: started
      ignore_errors: "{{ ansible_check_mode }}"

  handlers:
    - name: "server restart"
      become: true
      ansible.builtin.service:
        name: "apache2"
        state: restarted
      ignore_errors: True
